### ISSUE TITLE
Hardcoded sendgrid Api

### ISSUE THREAD

**Issue by ashikmeerankutty** [jamesgeorge007/Personal-Webapp#16]
Hardcoding API Keys may open your API keys to the public better to store your API keys and other sensitive information in the env file.
![screen shot 2018-10-27 at 12 37 58 am](https://user-images.githubusercontent.com/10515204/47587614-0902ff00-d981-11e8-801d-9a4980bb5ca9.jpg)

**Comment by jamesgeorge007** [comment]
:+1:
